name: Release

on:
  release:
    types: [released]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
            ubuntu-latest
          ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_BUILD: cp37-* cp38-* cp39-* cp310-*
          CIBW_SKIP: "*-musllinux*"
          CIBW_ARCHS: native
      - name: Save wheels
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  # https://cibuildwheel.readthedocs.io/en/stable/deliver-to-pypi/
  upload:
    name: Upload wheels to PyPI
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
